name: Update workshop template
on:
  push:
    branches:
      - main

jobs:
  update_packages:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update template
      run: |
        git config --global user.name "sinedied"
        git config --global user.email "noda@free.fr"
        ./scripts/create-github-template.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
